name: rtd-test-code
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - pandas
  - numpy
  - scipy
  - librosa
  - seaborn
  - pip
  - ipython
  - jupyter
  - pip:
    - opencv-python
    - ffmpeg
    - soundfile
    - torch
    - praat-parselmouth
